create table Sensor(
	id int generated by default as identity primary key, 
	name varchar (100) unique not null 
);

create table measurements (
	id int generated by default as identity primary key,
	sensor_id int references Sensor(id) on delete set null,
	value int check (value > -100 and value < 100),
	raining BOOLEAN NOT NULL
	
);

select * from sensor;
select * from measurements;

